### PR TITLE
Better choice of wording on the sx message

### PR DESCRIPTION
**Pull request by Reisyukaku**

### CODE REVIEW

**Comment by WerWolv98** [comment]
Yeah with you implementing the tx service, it will flag ReiNX users as well. I'm glad to accept the changes but the wording will still be off like that. So either you have to rename that service to something else and patch whatever uses it, give me an option to detect ReiNX or change the wording to "EdiZon detected the usage of SX OS or ReiNX". I don't really like the last option though because ReiNX never caused any issues so far

**Comment by Reisyukaku** [comment]
Hmm, glad you're willing to work things out .. I could add a reinx service so you could do something like
```C
if(!getServiceHandle("rnx")) {
    if(getServiceHandle("tx")) Popup();
}
```

**Comment by WerWolv98** [comment]
I'm totally fine with that if you can add that. The warning is purely to stop all those hateful messages from SX users that didn't read the warning and messed up stuff.

Tell me when you've implemented something and I'll redo the message and add that check :)

**Comment by Reisyukaku** [comment]
ok, that should be good
https://github.com/Reisyukaku/NX_Sysmodules/commit/fbfeb7f9333019aeb36a92183f4eae2e06172ae6

**Pull request closed without merging**
